services:
  postgres:
    image: postgres:16
    container_name: weather_postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT_EXTERNAL}:${POSTGRES_PORT_INTERNAL}"
    volumes:
      - weather_pgdata:/var/lib/postgresql/data

volumes:
  weather_pgdata:
